server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///${user.home}/project/personal/study/spring-cloud-native-file-repo
        git:
          uri: https://github.com/songjinhoon/spring-cloud-config.git
#          uri: file://C:/Users/hoons/project/personal/study/git-local-repo
#         만약 private repository 라면 아래 명시.
#         username: []
#         password: []

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh